#!/bin/zsh
# ================================================
# CREATE-JOB =====================================
# ================================================

# .env
# ------------------------------------------------
if ! test -f .env; then
  echo "fatal: .env does not exist"
  exit 1
fi

source .env

# Copy Example
# ------------------------------------------------
cp experiment_env_example.json experiment_env.json

echo "Edit 'experiment_env_example.json' then press ENTER"
read

echo "Creating job in 5 seconds... (Ctrl-C to abort)"
sleep 5

# Create Job
# ------------------------------------------------
_name=`date +%Y-%m-%d+%H:%M:%S`

# TEMPORARY:
_experiment_env_arg="'`cat experiment_env.json | tr -d '\n' | tr -d ' '`'"

paperspace jobs create \
  --project "Matching" \
  --name $_name \
  --experimentEnv $_experiment_env_arg \
  --customMetrics "testMetric1,testMetric2" \
  --container "paperspace/fastai:1.0-CUDA9.2-base-3.0-v1.0.6" \
  --machineType "P5000" \
  --command "/paperspace/run.sh" \
  --workspace "https://github.com/eriknomitch/matching.git" \
  --workspaceUsername $GITHUB_USERNAME \
  --workspacePassword $GITHUB_PERSONAL_ACCESS_TOKEN
