#!/bin/zsh

source .env

_name=`date +%Y-%m-%d+%H:%M:%S`

paperspace jobs create \
  --project "Matching" \
  --name $_name \
  --customMetrics "testMetric1,testMetric2" \
  --container "Paperspace + Fast.AI (JupyterLab BETA)" \
  --machineType "GPU+" \
  --command "/paperspace/run.sh" \
  --workspace "https://github.com/eriknomitch/matching.git" \
  --workspaceUsername $GITHUB_USERNAME \
  --workspacePassword $GITHUB_PERSONAL_ACCESS_TOKEN
