#!/bin/zsh
# ================================================
# CREATE-JOB =====================================
# ================================================

# .env
# ------------------------------------------------
if ! test -f .env; then
  echo "fatal: .env does not exist"
  exit 1
fi

source .env

# RUN_NUM
# ------------------------------------------------
RUN_NUM=$1

if test -z $RUN_NUM; then;
  echo "fatal: $0 <RUN_NUM>"
  exit 1
fi

# Create Job
# ------------------------------------------------
_date=`date +%Y-%m-%d+%H:%M:%S`
_name=$RUN_NUM

echo "Creating Paperspace job RUN_NUM=${RUN_NUM}"

paperspace jobs create \
  --project "Matching" \
  --name $_name \
  --experimentEnv "{\"FOO\": \"Bar\"}" \
  --customMetrics "testMetric1,testMetric2" \
  --container "paperspace/fastai:1.0-CUDA9.2-base-3.0-v1.0.6" \
  --machineType "P5000" \
  --command "RUN_NUM=$RUN_NUM bash -c '/paperspace/run.sh'" \
  --workspace "https://github.com/eriknomitch/matching.git" \
  --workspaceUsername $GITHUB_USERNAME \
  --workspacePassword $GITHUB_PERSONAL_ACCESS_TOKEN
